# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define "ubuntu" do |vm1|
    vm1.vm.box = "ubuntu/trusty64"
    vm1.vm.network "forwarded_port", guest: 22, host: 2223
  end
  config.vm.define "centos" do |vm2|
    vm2.vm.box = "centos/7"
    vm2.vm.network "forwarded_port", guest: 22, host: 2224
  end
end
